### ISSUE TITLE
[Question] Running celery worker in a different server

### ISSUE THREAD

**Issue by renartius** [saasitive/docker-compose-django-celery-redis-postgres#1]
Hi,
I really appreciate your article, it has helped me a lot. Thanks.
But I have a little question, how can I make worker running in a different server?

Sorry for my English.

**Comment by pplonski** [comment]
Hi @renartius,

You need to expose connection to Redis and database in docker-compose to be able to connect from worker on different machine or you can use hosted service for Redis and database.
