### ISSUE TITLE
add celery beat to worker

### ISSUE THREAD

**Issue by olikra** [saasitive/docker-compose-django-celery-redis-postgres#2]
Hi, 
first: This tutorial in context of Django,Celery and Docker ist one of the best ones available. Thanks so much for it.

In my project I have not to deal with triggering tasks by the UI - myy use case ist more to trigger tasks by celery beat (every minute, every hour, once per day,...). Is my understanding correct, to start the beat-worker inside the worker container via the script, where the worker process gets started?

Thanks a lot for your work.

Regards
olikra

**Comment by pplonski** [comment]
Thank you! Yes, you are correct, you need to start beat service in the container.

**Comment by olikra** [comment]
Thx...
