### ISSUE TITLE
/app/docker/backend/worker-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by arkhbum** [saasitive/docker-compose-django-celery-redis-postgres#4]
when I run docker-compose up: 
docker-compose-django-celery-redis-postgres-worker-1  | exec /app/docker/backend/worker-entrypoint.sh: no such file or directory
docker-compose-django-celery-redis-postgres-server-1  | exec /app/docker/backend/server-entrypoint.sh: no such file or directory
what could be wrong?

**Comment by pplonski** [comment]
have you added server-entrypoint.sh to docker image?

**Comment by arkhbum** [comment]
yes, I cloned the repo and tried to run locally without any changes

**Comment by pplonski** [comment]
hmmm, in the message you have information that file is missing, please double check if it is added to docker container. In the repo, without any changes, it should be added ...

**Comment by arkhbum** [comment]
![image](https://github.com/saasitive/docker-compose-django-celery-redis-postgres/assets/92441987/776cc14e-06d5-4460-8f2a-3f83b96e7b37)

**Comment by arkhbum** [comment]
that's the point: files exist, permissons granted

**Comment by pplonski** [comment]
Good. Try to list files in the docker image before running entrypoint scripts.

**Comment by rudotcom** [comment]
Permissions are being changed correctly in docker container. That's what confuses me

**Comment by hgf777-br** [comment]
I am having the same issue. Has someone found what's wrong?

**Comment by pplonski** [comment]
Hi @hgf777-br,

Please make sure that file is in docker container and has execution rights. You can check this by running `RUN ls -al` at the end of docker build.

**Comment by hgf777-br** [comment]
Hi, @pplonski ,

Thanks for your answer. Yes I had already checked. The files are there and the rights are ok. Really strange.... For the moment I moved the code from the scripts to the compose file. I was in a hurry to try some things. When I get some time I will try to check why those scripts are not working.
